# Generated by Django 4.2.2 on 2023-06-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_usercomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
