# Generated by Django 4.2.2 on 2023-06-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_fist_name_usercomments_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
                ('descrption', models.CharField(max_length=200)),
            ],
        ),
    ]
