# Generated by Django 4.2.2 on 2023-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_bookingdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingDate',
            new_name='Bookings',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
