# Generated by Django 4.2.2 on 2023-07-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_bookingdate_bookings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
